import { TimelineChart } from './components/timelineChart.js';
import { JurisdictionChart } from './components/jurisdictionChart.js';
import { DemographicChart } from './components/demographicChart.js';

let masterDataset = [];
let chartInstances = {};

const appState = {
    currentCategory: "mobile_phone",
    selectedJurisdiction: "All",
    selectedYear: "2024",
    selectedMethod: "All"
};

// Step 1: Ingest the unified dataset generated by KNIME
d3.csv("data/compiled_enforcement_data_2024.csv").then(data => {
    masterDataset = data;
    initializeDashboard();
}).catch(err => console.error("Pipeline Ingestion Engine Failed to process data file:", err));

function initializeDashboard() {
    // Instantiate concrete instances of the D3 Chart Components
    chartInstances.timeline = new TimelineChart("#timeline-chart");
    chartInstances.jurisdiction = new JurisdictionChart("#jurisdiction-chart", handleStateSelection);
    chartInstances.demographics = new DemographicChart("#demographic-chart");

    // UI Dispatcher: Category Navigation Tabs (PowerBI Mockup replication)
    d3.selectAll(".nav-tab").on("click", function() {
        d3.selectAll(".nav-tab").classed("active", false);
        d3.select(this).classed("active", true);

        appState.currentCategory = d3.select(this).attr("data-category");
        resetGeographicFilter();
        dispatchDataUpdate();
    });

    // UI Dispatcher: Left Panel Geographic Selector
    d3.select("#filter-state").on("change", function() {
        appState.selectedJurisdiction = d3.select(this).property("value");
        dispatchDataUpdate();
    });

    // UI Dispatcher: Horizontal Ribbon Year Selector
    d3.select("#filter-year").on("change", function() {
        appState.selectedYear = d3.select(this).property("value");
        dispatchDataUpdate();
    });

    // UI Dispatcher: Horizontal Ribbon Method Selector
    d3.select("#filter-method").on("change", function() {
        appState.selectedMethod = d3.select(this).property("value");
        dispatchDataUpdate();
    });

    // Global Interaction UI Reset Button
    d3.select("#btn-reset").on("click", () => {
        appState.selectedYear = "2024";
        appState.selectedMethod = "All";
        resetGeographicFilter();

        d3.select("#filter-year").property("value", "2024");
        d3.select("#filter-method").property("value", "All");

        dispatchDataUpdate();
    });

    // Fire the initial dashboard presentation layer execution pass
    dispatchDataUpdate();
}

// Linked Brushing bidirectional callback routine
function handleStateSelection(stateName) {
    appState.selectedJurisdiction = (appState.selectedJurisdiction === stateName) ? "All" : stateName;
    d3.select("#filter-state").property("value", appState.selectedJurisdiction);
    dispatchDataUpdate();
}

function resetGeographicFilter() {
    appState.selectedJurisdiction = "All";
    d3.select("#filter-state").property("value", "All");
}

function dispatchDataUpdate() {
    // Step 2: D3 parses the single CSV array efficiently using criteria properties
    const filteredSlice = masterDataset.filter(d => {
        const matchCategory = d.Fine_Category === appState.currentCategory;
        const matchState = appState.selectedJurisdiction === "All" || d.Jurisdiction === appState.selectedJurisdiction;
        const matchYear = appState.selectedYear === "All" || d.Year === appState.selectedYear;
        const matchMethod = appState.selectedMethod === "All" || d.Detection_Method === appState.selectedMethod;

        return matchCategory && matchState && matchYear && matchMethod;
    });

    // Step 3: Broadcast out to chart visual layers
    chartInstances.timeline.update(filteredSlice, appState.selectedJurisdiction);
    chartInstances.jurisdiction.update(filteredSlice, appState.selectedJurisdiction);
    chartInstances.demographics.update(filteredSlice);

    // Concurrently handle Left-Pane KPI aggregation
    const totalVolume = d3.sum(filteredSlice, d => +d.Infringement_Count || 0);
    d3.select("#kpi-total-volume").text(totalVolume.toLocaleString());
}